apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-shorts-bot
  labels:
    app: yt-shorts-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt-shorts-bot
  template:
    metadata:
      labels:
        app: yt-shorts-bot
    spec:
      containers:
      - name: yt-shorts-bot
        image: sumannath/yt-shorts-bot:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: yt-shorts-bot-svc
spec:
  type: NodePort
  selector:
    app: yt-shorts-bot
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
